name: Packer Unit Tests

on:
  push:
    paths:
      - 'infrastructure-configured-vms/**'
  pull_request:
    paths:
      - 'infrastructure-configured-vms/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  packer-unit-test-iis-vm:
    name: Packer Unit Tests IIS VM
    runs-on: ubuntu-latest

    env:
      working_directory: ./infrastructure-configured-vms
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Packer
      uses: hashicorp/setup-packer@main

    - name: Init Packer
      run: packer init ./iis-vm.pkr.hcl
      working-directory: ${{ env.working_directory }} 

    - name: Packer Format
      run: packer fmt
      working-directory: ${{ env.working_directory }} 

    - name: Validate Packer
      run: packer validate ./iis-vm.pkr.hcl
      working-directory: ${{ env.working_directory }} 

    - name: Validate Packer Build Agent
      run: packer validate ./iis-vm.pkr.hcl
      working-directory: ${{ env.working_directory }} 
